Medical-AI-Lab/Nervus

config/model.py
test.py
test_deepsurv.py
test_multi.py
train.py
train_deepsurv.py
train_multi.py
visualize.py

Integrated mlp_cnn.py and mlp_cnn_multi.py into model.py

Merge model single multi

---

test.py
train.py

Integrated train.py and train_multi.py into train.py.
Integrated test.py and test_multi.py into test.py.
In code for train, the part of for-loop of epoch was rewritten to functions,
which can be switched depending on single-label or multi-label.
In code for test, the whole part of inference was rewritten to functions,
which can be switched depending on single-label or multi-label.
WIP:
Now, roc.py and roc_multi.py should be integrated, and also yy.py and yy_yy_multi.py should be done.

Integrate codes for single-label and those for multi-label.

---

Makefile
evaluation/roc.py
evaluation/yy.py
lib/align_env.py
lib/util.py
work_all.sh

・Integrated roc.py and roc_multi.py to roc.py, where auc of each label is stored dataclasses.dataclass of python,
in addition, AUC is stored results/roc/summary/summary.csv.
In a similar fashion, yy.py and yy_multi.py have been integrated to yy.py, in addition, metrics of yy is stored results/yy/summary/summary.csv.
・In lib/align_env.py, add directories to store AUC or metrics of yy to the function set_dirs() in the following:
```
dirs_dict['roc_summary'] = os.path.join(dirs_dict['roc'], 'summary')
dirs_dict['yy_summary'] = os.path.join(dirs_dict['yy'], 'summary')
```
・In lib/util.py, deleted unnecessary lines in the function save_train_options().
・In work_all.sh, 
- deleted train_multi.py. test_multi.py, roc_multi.py and yy_multi.py since they have been merged.
- executing roc.py or …

Merge roc.py and roc_multi.py, and also yy.py and yy_multi.py.

---

Makefile
config/criterion.py
dataloader/dataloader.py
dataloader/dataloader_deepsurv.py
dataloader/dataloader_multi.py
evaluation/c_index.py
lib/align_env.py
test.py
train.py
work_all.sh

- Integrated config/criterion_deepsurv.py into config/criterion.py.
- Integrated train_deepsurv.py into train.py.
- Integrated test_deepsurv.py into test.py.
- In lib/align_env.py, `csv_dict['label_name']` was deleted.
`label_name ` can be referred as  `csv_dict['label_list']`.
- With respect to dataloader/dataloader.py, dataloader/dataloader_multi.py, and dataloader/dataloader_deepsurv.py, `csv_dict['label_name']` was deleted.
- Modified c_index.py so that c-index would be stored in results/c_index/summary/summary.csv while executing work_all.sh.
- In lib/align_env.py, the directories results/c_index and results/c_index/summary/ are defined freshly.
- Modified Makefile by adding the target `c_index`.
- In works_all.sh, c_index.py was added, then plotting ROC,  plotting yy-graph, and …

Integrated Deepsurv into Nervus.

---

config/criterion.py
config/model.py
config/optimizer.py
dataloader/dataloader.py
dataloader/dataloader_deepsurv.py
dataloader/dataloader_multi.py
evaluation/c_index.py
evaluation/roc.py
evaluation/yy.py
lib/align_env.py
test.py
train.py

- align_env.py:
Modified so that label names would be made from column name which are like `output_XXX` of CSV, and then labels would be made depending on the number of classes in the column.
For example, let `output_1, output_2, ...`  be columns. Labels are then `label_output_1, label_output_2, ...` When classes `class_1, class_2, class_3, ...` are in the column `output_1`, labels `0, 1, 2, ...` are supposed to in the column `label_otuput_1`. 
- dataloader.py, dataloader_multi.py and dataloader_deepsurv.py:
As how to make label was modified in align_env.py, they were modified so that value of `output_XXX` of CSV would be returned. In addition, renamed `MakeDataLoader_MLP_CNN_with_WeightedRandomSampler()` `dalaloader_mlp_cnn()`.
And also, `exit()`was replaced with assert.
- …

Modified so that Nervus could handle multi-class classification.

---

Makefile
config/criterion.py
config/model.py
evaluation/c_index.py
evaluation/roc.py
evaluation/yy.py
lib/align_env.py
lib/util.py
options/test_options.py
options/train_options.py
options/visualize_option.py
test.py
train.py
visualize.py
work_all.sh

**Makefile**
Deleted unnecessary directories due to the reconstruction of directories of results.
**config/criterion.py**
Renamed `CrossEntropyLoss` `CEL`.
**config/model.py**
Replaced `set_device()` with `set_device()` defined in `lib/util.py`.
Deleted `config_device()`.
**evaluation/c_index.py**
Modified so that `c_index.csv` would be saved in `results/yyyy-mm-dd-HH-MM-SS/`.
Deleted unnecessary variables due to the reconstruction of directories of results.
**evaluation/roc.py**
Modified so that `roc.png` would be saved in `results/yyyy-mm-dd-HH-MM-SS/`.
Deleted unnecessary variables due to the reconstruction of directories of results.
**evaluation/yy.py**
Modified so that `yy.png` would be saved in `results/yyyy-mm-dd-HH-MM-SS/`.
Deleted unnecessary variables due to the reconstruction …

Reconstructed the directory of results.

---

.editorconfig
.gitignore
Pipfile
Pipfile.lock

- make editorconfig
- add black and flake8 to pipenv

Add format and linter config 

---

Makefile
README.md
dataloader/dataloader.py
dataloader/dataloader_deepsurv.py
dataloader/dataloader_multi.py
hyperparameters/hyperparameter.csv
lib/align_env.py
lib/util.py
options/train_options.py
parameters/parameter.csv
test.py
train.py
work_all.sh

Add options to apply all augmentations.
By specifying `--augmentation 'yes'` in training, all augmentation are applied.
Note that all the augmentations are not applied in test by ` train_parameters['preprocess'] = 'no'` in `test.py `.
In addition,
Renamed `hyperparameter/hyperparameter.csv`  `parameters/parameter.csv`.
Renamed `materials/csvs`  `materials/splits`.

Add options to apply all augmentations.

---

.editorconfig
README.md
config/criterion.py
config/model.py
config/optimizer.py
evaluation/c_index.py
evaluation/roc.py
evaluation/yy.py
lib/util.py
options/train_options.py
test.py
train.py

Add: Wrapper class of logging module for Nervus.

---

config/__init__.py
config/criterion.py
config/model.py
config/optimizer.py
dataloader/__init__.py
dataloader/dataloader_deepsurv.py
dataloader/dataloader_multi.py
evaluation/c_index.py
evaluation/roc.py
evaluation/yy.py
lib/__init__.py
lib/util.py
options/__init__.py
options/metrics_options.py
options/test_options.py
options/train_options.py
test.py
train.py

convert module to package.

---

lib/align_env.py

NervusEnvのtypo修正

---

Makefile
README.md
evaluation/c_index.py
evaluation/roc.py
evaluation/yy.py
lib/align_env.py
options/train_options.py
test.py
train.py
work_all.sh

modified:   Makefile
modified:   evaluation/roc.py
modified:   evaluation/yy.py
modified:   evaluation/c_index.py
modified:   lib/align_env.py
modified:   options/train_options.py
Based on `save_weight`, weight is saved. When multi-label output, weight is saved each time total loss decreases.
At the start of training, `save_data_dir/weights/` is made.
Inference is done by using each weight and csv of likelihood is made for each weight.
ROC or yy-plot is made for each likelihood.

WIP: Modifying so that weight would be saved each time epoch loss decreases when multi-label.

---

dataloader/dataloader_deepsurv.py
dataloader/dataloader_multi.py
dataloader/dataloader_single.py
dataloader/nervus_dataloader.py
evaluation/c_index.py
evaluation/roc.py
evaluation/yy.py
lib/align_env.py
test.py
train.py

modified:   dataloader/dataloader_deepsurv.py
modified:   dataloader/dataloader_multi.py
modified:   dataloader/dataloader_single.py
modified:   dataloader/nervus_dataloader.py
modified:   evaluation/roc.py
modified:   evaluation/yy.py
modified:   evaluation/c_index.py
modified:   lib/align_env.py
- The columns of `Institution` and `ExamID` have to be included in split.csv. 
- CSV of likelihood includes The columns of `Institution` and `ExamID`.
- ROC, yy-plot, and c-index are made for each institution.
- `summary.csv` is updated institution-wise.

WIP: Add columns of Institution and ExamID.

---

models/dataloader.py
models/framework.py
models/loss.py
models/net.py
models/options.py
test.py
train.py

Refactored codes to save or load paramaters by incorporating a variable isTrain.
modified:   models/dataloader.py
modified:   models/framework.py
modified:   models/loss.py
modified:   models/net.py

Refactoring test.py.

---

eval.py
metrics/c_index.py
metrics/roc.py
metrics/yy.py
models/env.py
models/options.py
test.py

modified:   metrics/roc.py
modified:   metrics/yy.py
modified:   metrics/c_index.py
Refactored code to calculate ROC both for binary classes and multi-class.
Refactored code to calculate yy-graph.
Refactored code to calculate c-index.

Refactoring eval.py.

---

eval.py
metrics/c_index.py
metrics/roc.py
metrics/yy.py
models/env.py
models/framework.py
models/options.py
test.py
train.py

modified:   models/env.py
modified:   metrics/roc.py
modified:   metrics/yy.py
modified:   metrics/c_index.py
modified:   models/framework.py
Modified how to print metrics in roc.py, yy.py, and c_index.py.
Refactored  c_index.py.
Refactored  test.py.

Refactor test.py.

---

Makefile
models/dataloader.py
models/options.py

And also, modified so that augmentation would not apply to validation dataset when traning.
modified:   models/dataloader.py
modified:   Makefile

Add augmentation list for X-ray in dataloader.py

---

.gitignore
logs/README.md
work_all.sh

new file:   logs/README.md
modified:   .gitignore

Modified work_all.sh.

---

eval.py
logger/__init__.py
logger/logger.py
metrics/__init__.py
metrics/c_index.py
metrics/roc.py
metrics/yy.py
models/__init__.py
models/dataloader.py
models/env.py
models/framework.py
models/loss.py
models/net.py
models/optimizer.py
models/options.py
test.py
train.py

new file:   logger/__init__.py
modified:   models/__init__.py
modified:   metrics/__init__.py
modified:   logger/logger.py
modified:   models/env.py
modified:   models/dataloader.py
modified:   models/net.py
modified:   models/loss.py
modified:   models/optimizer.py
modified:   models/framework.py
modified:   metrics/roc.py
modified:   metrics/yy.py
modified:   metrics/c_index.py
Cleaned up import statements from logger/, models/, and metrics/.
Replaced
```
import sys
sys.path.append((Path().resolve() / '../').name)
from logger.logger import Logger
```
to 
`import logger`
by adding `logger/__init__.py.`

Cleaned up import statements in each file.

---

models/framework.py
test.py

modified:   models/framework.py
Added `ExamID `columns

Modify likelihood.

---

models/options.py
parameter.csv
work_all.sh

modified:   parameter.csv
And also modified so that `gpu_ids` would be specified like 0, 0-1-2, 0-2.

Modified so that save_weight and gpu_ids could be specified in paramaremeter.csv

---

eval.py
test.py
train.py
work_all.sh

Added `if __name__ == '__main__'` .

Modularization

---

eval.py
lib/__init__.py
lib/criterion.py
lib/dataloader.py
lib/env.py
lib/framework.py
lib/likelihood.py
lib/logger.py
lib/loss.py
lib/net.py
lib/optimizer.py
lib/options.py
logs/README.md
metrics/c_index.py
metrics/roc.py
metrics/yy.py
test.py
train.py
work_all.sh

deleted:    logs/README.md
modified:   lib/logger.py
modified:   lib/dataloader.py
modified:   lib/likelihood.py
modified:   lib/loss.py
modified:   lib/net.py
modified:   lib/__init__.py
modified:   metrics/c_index.py
modified:   metrics/roc.py
modified:   metrics/yy.py

Refactored logger so that logger would be handled as global.

---

lib/dataloader.py
lib/options.py

modified:   lib/dataloader.py
And also, class LoadDataSet() was devided into three Mixin classes, InputValueMixin, ImageMixin and DeepSurvMixin
because class LoadDataSet() was too long to read.
Modified help of --model option.

Add normalization of tabular data in dataloader.

---

Makefile

Merged Makefile in main into test_external_dataset.

Fixed the notation of how to specify GPUs.

---

lib/component/dataloader.py
lib/component/likelihood.py
lib/metrics.py
work_all.sh

modified:   lib/component/likelihood.py

Modified so that label assigned integer in csv could be handled.

---

Makefile
eval.py
lib/component/dataloader.py
lib/component/likelihood.py
lib/component/loss.py
lib/component/net.py
lib/component/optimizer.py
lib/framework.py
lib/logger.py
lib/metrics.py
lib/options.py
parameter.csv
test.py
train.py
work_all.sh

・Added several options so that test could handle external dataset.
・Deleted raw_label, internal_label.
・Deleted --image_dir.
・Deleted --baseset_dir, --testset_dir, --test_datetime.
・parameter is saved as paramater.json.
・scaler function(=MinMaxScaler()) is saved as pickl.
・Renamed --save_weight -> --save_weight_policy.
・Created class ModelParam in framework.py.
・Could handle csv with no column of label when used external dataset.
・In lib/framework.py, added argument in create_model(), create_model(..., test_splits: List[str], likelihood_on: bool).
modified:   lib/component/net.py
modified: …

Handle external dataset.

---

Makefile
lib/component/dataloader.py
lib/framework.py
lib/options.py
work_all.sh

・For specifying GPU ids. at test.
modified:   Makefile
・For fixing bug the dimentsion `input_values`.

Modified so that gup_ids could be specified at test apart from at training.

---

README.md
lib/__init__.py
lib/component/dataloader.py
lib/component/likelihood.py
lib/framework.py
lib/options.py
test.py
train.py

modified:   lib/`__init__.py`
modified:   lib/component/likelihood.py
README.md

Separating class of parameter, dataloader, and likelihood from model class.

---

eval.py
lib/__init__.py
lib/component/__init__.py
lib/component/loss.py
lib/framework.py
lib/logger.py
lib/metrics.py
test.py
train.py

modified:   lib/logger.py
modified:   lib/`__init__.py`
modified:   lib/component/`__init__.py`
modified:   lib/component/loss.py

Modified so that error would be written to file.

---

lib/component/dataloader.py
lib/component/likelihood.py
lib/framework.py
lib/metrics.py

modified:   lib/component/likelihood.py

Add column of group if it is not in csv.

---

README.md
eval.py
lib/framework.py
lib/logger.py
lib/metrics.py
lib/options.py
work_all.sh

・Rename 'sets' to 'trials'.
・Add 'project' to parameters.
・Move materials/results to Nervus/results/<project>/trials/<datetime_name>
・Deleted variables named _dataset_dir and _csv_name.
modified:   lib/logger.py
modified:   README.md

Add project and move directory results.

---

lib/logger.py

・Modified filter of file handler of logger.
modified:   lib/logger.py

Modify filter of logger.

---

lib/component/dataloader.py
lib/options.py
test.py
train.py

Additional modification has been done.

Organize parameters again

---

eval.py
lib/__init__.py
lib/component/__init__.py
lib/component/criterion.py
lib/component/likelihood.py
lib/component/loss.py
lib/component/net.py
lib/component/optimizer.py
lib/dataloader.py
lib/framework.py
lib/metrics.py
lib/options.py
test.py
train.py

・Modified set_data() in framework.py so that it could return period and network when deepsurv.
・Then, modified so that the difference of arguments between criterions would be wrapped in criterion.py.
・Deleted class ClsLss, class RegLoss, and class DeepSurvLoss in loss.py by .
・Deleted class MLPDeepSurv, CVDeepSurv, and FusionDeepSurv in framework.py.
・Modified so that epoch would start 1, not 0.
・main() takes keyword arguments in train.py and test.py.
・Organized cast of inputs, label, and periods in dataloader.py, criterion.py.
・Added function to check if criterion is valid for task in options.py.
・Updated parameter table in options.py.
modified:   `lib/component/__init__.py`
modified:   lib/component/criterion.py
modified:   lib/component/loss.py
modified:   lib/component/optimizer.py …

Refactor loss.py

---

Makefile
README.md
lib/__init__.py
lib/component/criterion.py
lib/component/loss.py
lib/dataloader.py
lib/framework.py
lib/options.py
parameter.csv
test.py
train.py

modified:   `lib/__init__.py`
modified:   lib/dataloader.py
modified:   lib/component/loss.py
modified:   lib/component/criterion.py
modified:   parameter.csv
modified:   README.md
modified:   Makefile
・options.py:
Changed how to specify sampler like `--sampler { weighted, distributed, distweight, no}`
Added function to return elapsed time.
・framework.py
Added function to initialize distributed process group.
・dataloader.py:
Incorporated DistributedSampler and DistributedWeightedSampler.
・loss.py
Added a instance variable in LossStore to count total number of data learned at phase in each epoch.
・criterion.py:
Incorporated early return.
・train.py
Incorporated  DistributedDataParallel.
Modified …

Incorporating DistributedDataParallel.

---

README.md
eval.py
lib/metrics.py
lib/options.py

modified:   README.md
・options.py
Changed from `--weight_dir` to `--weight`.
・eval.py
Changed from  `--likelihood_dir` to `--likelihood`.

Change how to specify weight and likelihood

---

lib/component/net.py
lib/component/optimizer.py
lib/options.py
test.py
train.py

modified:   lib/component/net.py
modified:   lib/component/optimizer.py
・options.py
option `--sampler` is required, or must be specified explicitly.
・net.py
early return
avoid having unnecessary network objects

Refactor ney.py
